site_name: HIN Gateway - Logiciels et documentation
site_url: https://Health-Info-Net-AG.github.io/stargate-deployment/
site_author: HIN AG
site_description: >-
  Stargate deployment User Dokumentation. Docker, Helmcharts, Virtual Machine, Azure, usw.

docs_dir: "../../docs/fr"
site_dir: "../../site/fr"

# Repository
repo_name: Health-Info-Net-AG/Stargate-deployment
repo_url: https://github.com/Health-Info-Net-AG/Stargate-deployment
edit_uri: edit/main/docs/fr/

# Copyright
copyright: Copyright HIN AG 2026

# Configuration
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    primary: orange
  logo: assets/hin_logo_full.png
  language: fr

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/hin_logo.png
  icon:
    alternate: material/web
  #  logo: logo

# Plugins
plugins:
  #  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox
  - redirects:
      redirect_maps:
        "vm/VM-images-list.md": "vm/VM-Catalog.md"
        "Testing.md": "index.md"
#        'old/file.md': 'new/file.md'
#        'some_file.md': 'http://external.url.com/foobar'
  - print-site

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Health-Info-Net-AG/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/healthinfonetag/
  alternate:
    - name: English
      link: /Stargate-deployment/en/
      lang: en
    - name: Deutsch
      link: /Stargate-deployment/de/
      lang: de
    - name: French
      link: /Stargate-deployment/fr/
      lang: fr
    - name: Italian
      link: /Stargate-deployment/it/
      lang: it

extra_javascript:
  - javascripts/tablesort.min.js
  - javascripts/tablesort.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
#      auto_append:
#        - docs/fr/includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

not_in_nav: |
  assets/*.md
  includes/*.md

# Page tree
nav:
  - Home: index.md
  - Guides d'installation:
      - Domaine unique, M365: Installation-guide.md
  #      - Nouveaux clients: New-customers.md
  - Configuration technique et Intégration:
      - Aperçu des applications: Applications.md
      - Surveillance et Logs: Monitoring.md
      - Intégration Exchange: Exchange-integration.md
      - Configuration du relais de courrier: Mail-relay-setup.md
      - Configuration DNS: DNS-setup.md
  - Installation serveur:
      - Conteneur:
          - Installation avec Docker: Docker-deploy.md
          - Configuration avancée Docker: Docker-advanced.md
          - Déploiement Helm: helm-deploy.md
      - Déploiement VM:
          - Azure: vm/Azure-image-install.md
          - VMware: vm/VMware-image-install.md
          - Proxmox: vm/Proxmox-image-install.md
          - Windows 11 Pro: vm/Windows11pro-image-install.md
          - Cloudscale: vm/Cloudscale-image-install.md
  - Catalogue d'images VM: vm/VM-Catalog.md
  - Dépannage: Troubleshooting.md
  - Release Notes: Release-notes.md
  - Support / Contactez-nous: Support.md
