name: documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'config_docs/**'

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # https://github.com/actions/checkout/releases/tag/v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          # 0 is required to scan full git history
          fetch-depth: 10

      - name: Run Gitleaks on docs/
        # https://github.com/gacts/gitleaks/releases/tag/v1.3.2
        uses: gacts/gitleaks@c9a0338361dc45a01aa7ebaaa5330179f3c62873
        with:
          # Scan only the docs folder
          path: ./docs
          # Fail workflow if secrets found
          fail-on-error: true

  documentation:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        # https://github.com/actions/checkout/releases/tag/v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Get short SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Generate badge JSON
        run: sed -i "s/SHA/${{ steps.sha.outputs.sha }}/" docs/badges/build.json
        # Then badge can be used in text as ![commit](https://img.shields.io/endpoint?url=https://health-info-net-ag.github.io/Stargate-deployment/badges/build.json)

      - name: Build documentation - de
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/docs \
            --entrypoint sh \
            squidfunk/mkdocs-material \
            -c "pip install mkdocs-glightbox mkdocs-print-site-plugin && mkdocs build --clean -f config_docs/de/mkdocs.yml"

      - name: Build documentation - fr
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/docs \
            --entrypoint sh \
            squidfunk/mkdocs-material \
            -c "pip install mkdocs-glightbox mkdocs-print-site-plugin && mkdocs build --clean -f config_docs/fr/mkdocs.yml"

      - name: Build documentation - it
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/docs \
            --entrypoint sh \
            squidfunk/mkdocs-material \
            -c "pip install mkdocs-glightbox mkdocs-print-site-plugin && mkdocs build --clean -f config_docs/it/mkdocs.yml"

      - name: Build documentation - en
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/docs \
            --entrypoint sh \
            squidfunk/mkdocs-material \
            -c "pip install mkdocs-glightbox mkdocs-print-site-plugin && mkdocs build --clean -f config_docs/en/mkdocs.yml"

      - name: Fix ownership
        run: sudo chown -R runner:docker site

      # We will make EN default language and copy its content to the root folder too to keep old links working
      - name: Create default documentation in the root
        run: |
          cp -r site/en/* site/

      - name: Upload to GitHub Pages
        # https://github.com/actions/upload-pages-artifact/releases/tag/v5.0.0
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: site

      - name: Deploy to GitHub Pages
        # https://github.com/actions/deploy-pages/releases/tag/v5.0.0
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128